-- 20.12.31 Oracle 쇼핑몰 마켓 DB 만들기 실습


-- 1. CUSTOMER TABLE 생성

DROP TABLE CUSTOMER; -- TABLE 생성 전 겹치는 테이블 삭제

CREATE TABLE CUSTOMER (
    cID         VARCHAR2(10),
    cNAME       VARCHAR2(50)  NOT NULL,    
    cTEL        VARCHAR2(30)  UNIQUE,
    cADDRESS    VARCHAR2(255) NOT NULL,
    cEMAIL      VARCHAR2(40)  UNIQUE,
    
    PRIMARY KEY (cID)
);

SELECT * FROM CUSTOMER; -- TABLE 생성 확인

-- KEY IN
INSERT INTO CUSTOMER (cID, cNAME, cTEL, cADDRESS, cEMAIL)
    VALUES ('ABC','홍길동','010-1111-1111','서울 마포구','ABC@GMAIL.COM');

INSERT INTO CUSTOMER (cID, cNAME, cTEL, cADDRESS, cEMAIL)
    VALUES ('DEF','김길동','010-2222-2222','서울 서대문구','DEF@GMAIL.COM');

INSERT INTO CUSTOMER (cID, cNAME, cTEL, cADDRESS, cEMAIL)
    VALUES ('GHY','이길동','010-3333-3333','경기도 고양시','GHY@GMAIL.COM');

SELECT * FROM CUSTOMER; -- KEY IN 확인


-- 2. GOODS TABLE 생성

DROP TABLE GOODS; -- TABLE 생성 전 겹치는 테이블 삭제
    
CREATE TABLE GOODS (
    gCODE       VARCHAR2(10),
    gNAME       VARCHAR2(50)  UNIQUE,
    gPRICE      NUMBER(10)    NOT NULL,
    gSTOCK      NUMBER(5)     NOT NULL,
    
    PRIMARY KEY(gCODE) 
);

SELECT * FROM GOODS; -- TABLE 생성 확인

-- KEY IN
INSERT INTO GOODS (gCODE, gNAME, gPRICE, gSTOCK)
    VALUES ('A1','맥주', TO_NUMBER('2,000','9,999'), TO_NUMBER('1,000','9,999'));
    
INSERT INTO GOODS (gCODE, gNAME, gPRICE, gSTOCK)
    VALUES ('A2','소주', TO_NUMBER('1,500','9,999'), TO_NUMBER('1,000','9,999'));
    
INSERT INTO GOODS (gCODE, gNAME, gPRICE, gSTOCK)
    VALUES ('B1','땅콩', TO_NUMBER('3,000','9,999'), TO_NUMBER('1,500','9,999'));

INSERT INTO GOODS (gCODE, gNAME, gPRICE, gSTOCK)
    VALUES ('B2','오징어', TO_NUMBER('5,000','9,999'), TO_NUMBER('2,000','9,999'));

INSERT INTO GOODS (gCODE, gNAME, gPRICE, gSTOCK)
    VALUES ('C1','기저귀', TO_NUMBER('7,000','9,999'), TO_NUMBER('800','9,999'));

INSERT INTO GOODS (gCODE, gNAME, gPRICE, gSTOCK)
    VALUES ('C2','분유', TO_NUMBER('10,000','99,999'), TO_NUMBER('500','9,999'));

SELECT * FROM GOODS; -- KEY IN 확인


-- 3. BASKET TABLE 생성 (bNUM SEQUENCE 생성)

DROP TABLE BASKET; -- TABLE 생성 전 겹치는 테이블 삭제
    
CREATE TABLE BASKET (
    bNUM        NUMBER(10), 
    cID         VARCHAR2(10) NOT NULL,
    gCODE       VARCHAR2(10) NOT NULL,
    QTY         NUMBER(10)   NOT NULL,
    COST        NUMBER(10)   NOT NULL,
    
    PRIMARY KEY(bNUM),
    FOREIGN KEY(cID)   REFERENCES CUSTOMER(cID),
    FOREIGN KEY(gCODE) REFERENCES GOODS(gCODE)
);

SELECT * FROM BASKET;                 -- BASKET TABLE 생성 확인

DROP TABLE BASKET_SEQ;                -- TABLE 생성 전 겹치는 테이블 삭제

CREATE SEQUENCE BASKET_SEQ  -- SEQUENCE로 BASKET 번호를 자동생성
    MAXVALUE 999999 NOCYCLE NOCACHE;


-- 4. ORDER TABLE 생성

DROP TABLE ORDER_INFO;  -- TABLE 생성 전 겹치는 테이블 삭제

CREATE TABLE ORDER_INFO (
    oiNUM           NUMBER(10),
    cID             VARCHAR2(10)  NOT NULL,         
    oADDRESS        VARCHAR2(255) NOT NULL,
    oTEL            VARCHAR2(30)  NOT NULL,
    oDATE           DATE DEFAULT  SYSDATE,
    
    PRIMARY KEY(oiNUM),
    FOREIGN KEY(cID) REFERENCES CUSTOMER(cID) 
);

SELECT * FROM ORDER_INFO;  -- TABLE 생성 확인


-- 5. ORDER_LIST TABLE 생성

CREATE TABLE ORDER_LIST (
    olNUM       NUMBER(6),
    oiNUM       NUMBER(10)  NOT NULL,
    gCODE       VARCHAR2(10)NOT NULL,
    QTY         NUMBER(5)   NOT NULL,
    COST        NUMBER(10)  NOT NULL,
    
    PRIMARY KEY(olNUM),
    FOREIGN KEY(oiNUM)  REFERENCES ORDER_INFO(oiNUM),
    FOREIGN KEY(gCODE)  REFERENCES GOODS(gCODE)
);

SELECT * FROM ORDER_LIST; -- TABLE 생성 확인

DROP SEQUENCE ORDER_LIST_SEQ; -- TABLE 생성 전 겹치는 테이블 삭제

CREATE SEQUENCE ORDER_LIST_SEQ -- SEQUENCE로 ORDER_LIST 번호를 자동생성
    MAXVALUE 999999 NOCYCLE NOCACHE;

COMMIT; -- 생성된 모든자료 DB에 저장






    