-- 21.01.12 Supermarket SQL --

-- DROP 
DROP TABLE CUSTOMER; 
DROP TABLE CUS_LEVEL;
DROP SEQUENCE CUSTOMER_SEQ;


-- 테이블 생성

CREATE TABLE CUS_LEVEL(
    LEVELNO     NUMBER(1,0) PRIMARY KEY,
    LEVELNAME   VARCHAR2(20),
    LOW         NUMBER(9,0),
    HIGH        NUMBER(9,0));

CREATE TABLE CUSTOMER(
    CID         NUMBER(6,0)     PRIMARY KEY,
    CTEL        VARCHAR2(20)    NOT NULL,
    CNAME       VARCHAR2(30)    NOT NULL,
    CPOINT      NUMBER(9,0)     DEFAULT 1000,
    CAMOUNT     NUMBER(9,0)     DEFAULT 0,
    LEVELNO     NUMBER(1,0)     DEFAULT 1 REFERENCES CUS_LEVEL(LEVELNO));

CREATE SEQUENCE CUSTOMER_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;


-- 데이터 INSERT

INSERT INTO CUS_LEVEL VALUES (1, 'NORMAL', 0, 999999);
INSERT INTO CUS_LEVEL VALUES (2, 'SILVER', 1000000, 1999999);
INSERT INTO CUS_LEVEL VALUES (3, 'GOLD', 2000000, 2999999);
INSERT INTO CUS_LEVEL VALUES (4, 'VIP', 3000000, 4999999);
INSERT INTO CUS_LEVEL VALUES (5, 'VVIP', 5000000, 999999999);

SELECT * FROM CUS_LEVEL;

INSERT INTO CUSTOMER (cID, cTEL, cNAME) VALUES 
        (CUSTOMER_SEQ.NEXTVAL, '010-9999-9999', '홍길동');
INSERT INTO CUSTOMER VALUES
        (CUSTOMER_SEQ.NEXTVAL, '010-8888-9999', '김길동', 1000, 5000000,5);

COMMIT;


-- 0. LEVELNAME(레벨 이름들)

SELECT LEVELNAME FROM CUS_LEVEL ORDER BY LEVELNO;


-- 1. 고객 아이디 검색 

SELECT CID, CTEL, CNAME, CPOINT, CAMOUNT, LEVELNAME,
    (SELECT HIGH - CAMOUNT + 1 
        FROM CUSTOMER WHERE CID = C.CID AND LEVELNO != 5) forLEVELUP
    FROM CUSTOMER C, CUS_LEVEL L
    WHERE C.LEVELNO = L.LEVELNO AND cID = 2;  -- 자바에 쓸 SQL


-- 2. 전화번호 뒷자리 4자리검색=FULL검색

SELECT CID, CTEL, CNAME, CPOINT, CAMOUNT, LEVELNAME,
    (SELECT HIGH - CAMOUNT + 1 
        FROM CUSTOMER WHERE CID = C.CID AND LEVELNO != 5) forLEVELUP
    FROM CUSTOMER C, CUS_LEVEL L
    WHERE C.LEVELNO = L.LEVELNO and CTEL LIKE '%'||'9999'; --자바에서 쓸 SQL


-- 3. 고객 이름검색

SELECT CID, CTEL, CNAME, CPOINT, CAMOUNT, LEVELNAME,
    (SELECT HIGH - CAMOUNT + 1 
        FROM CUSTOMER WHERE CID = C.CID AND LEVELNO != 5) forLEVELUP
    FROM CUSTOMER C, CUS_LEVEL L
    WHERE C.LEVELNO = L.LEVELNO and CNAME = '홍길동'; --자바에서 쓸 SQL


-- 4. 포인트로 물품구매 

UPDATE CUSTOMER SET CPOINT = CPOINT - 500 WHERE CID = 1;

SELECT * FROM CUSTOMER;


-- 5. 물품구매 (포인트변경, 구매누적금액변경, LEVELNO변경)

-- 5-1 포인트와 구매누적금액 변경

UPDATE CUSTOMER SET CPOINT = CPOINT + 1000000 * 0.05,
                    CAMOUNT = CAMOUNT + 1000000
                WHERE CID = 1;

SELECT * FROM CUSTOMER;

-- 5-2 LEVELNO변경

SELECT CNAME, CAMOUNT, C.LEVELNO, L.LEVELNO, LOW, HIGH
    FROM CUSTOMER C, CUS_LEVEL L
    WHERE CAMOUNT BETWEEN LOW AND HIGH;

SELECT L.LEVELNO
    FROM CUSTOMER C, CUS_LEVEL L
    WHERE CAMOUNT BETWEEN LOW AND HIGH AND CID = 1; -- CID=1인 고객이 바꿔야 할 레벨

UPDATE CUSTOMER 
    SET LEVELNO = (SELECT L.LEVELNO
                    FROM CUSTOMER C, CUS_LEVEL L
                    WHERE CAMOUNT BETWEEN LOW AND HIGH AND CID = 1)
    WHERE CID = 1;

SELECT * FROM CUSTOMER;

COMMIT;

-- 5-1 + 5-2 합한 부분을 자바에 쓸 SQL로

UPDATE CUSTOMER SET CPOINT = CPOINT + 1000000*0.05,
                    CAMOUNT = CAMOUNT + 1000000,
                    LEVELNO = (SELECT L.LEVELNO
                                FROM CUSTOMER C, CUS_LEVEL L
                                WHERE CAMOUNT + 1000000 BETWEEN LOW AND HIGH AND CID = 1)
                WHERE CID = 1; -- 자바에 쓸 SQL

SELECT * FROM CUSTOMER;


-- 6. 고객 등급별 출력

SELECT CID, CTEL, CNAME, CPOINT, CAMOUNT, LEVELNAME,
    (SELECT HIGH - CAMOUNT + 1 
        FROM CUSTOMER WHERE CID = C.CID AND LEVELNO != 5) forLEVELUP
    FROM CUSTOMER C, CUS_LEVEL L
    WHERE C.LEVELNO = L.LEVELNO and LEVELNAME = 'VVIP'
    ORDER BY CAMOUNT DESC;


-- 7. 고객명단 전체 출력

SELECT CID, CTEL, CNAME, CPOINT, CAMOUNT, LEVELNAME,
    (SELECT HIGH-CAMOUNT+1 
        FROM CUSTOMER WHERE CID = C.CID AND LEVELNO != 5) forLEVELUP
    FROM CUSTOMER C, CUS_LEVEL L
    WHERE C.LEVELNO = L.LEVELNO 
    ORDER BY CAMOUNT DESC;


-- 8. 회원가입

INSERT INTO CUSTOMER (CID, CTEL, CNAME) VALUES
    (CUSTOMER_SEQ.NEXTVAL, '010-7777-7777', '신길동');

SELECT * FROM CUSTOMER;


-- 9. 전화번호 수정

UPDATE CUSTOMER SET CTEL = '010-7777-7771' WHERE CID = 3;

SELECT * FROM CUSTOMER;


-- 10. 회원탈퇴

DELETE FROM CUSTOMER WHERE CID = 3;

SELECT * FROM CUSTOMER;

COMMIT;

